config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('users.urls')),
    path('recipe/', include('recipe.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import (
    home_view,
    about_view,
    contact_view,
    terms_view,
)

app_name = 'core'

# Path: core/urls.py
urlpatterns = [
    path('', home_view, name='home'),
    path('about/', about_view, name='about'),
    path('contact/', contact_view, name='contact'),
    path('terms/', terms_view, name='terms'),
]

recipe/urls.py
from django.urls import path
from .views import (
    all_recipes_view,
    recipe_detail_view,
    new_recipe_view,
    update_recipe_view,
    delete_recipe_view,
    user_recipes_view,
    explore,
)

app_name = 'recipe'

# Path: recipe/urls.py
urlpatterns = [
    path('all/', all_recipes_view, name='all_recipes'),
    path('new/', new_recipe_view, name='new_recipe'),
    path('<int:recipe_id>/', recipe_detail_view, name='recipe_detail'),
    path('<int:recipe_id>/update/', update_recipe_view, name='update_recipe'),
    path('<int:recipe_id>/delete/', delete_recipe_view, name='delete_recipe'),
    path('user/<int:user_id>/', user_recipes_view, name='user_recipes'),
    path('explore/', explore, name="explore"),
]

recipe/models.py
from django.db import models
from django.contrib.auth import get_user_model
from ckeditor.fields import RichTextField

# Model for the recipe itself
class Recipe(models.Model):
    BREAKFAST = 'Breakfast'
    LUNCH = 'Lunch'
    DINNER = 'Dinner'
    DESSERT = 'Dessert'
    BEVERAGES = 'Beverage'
    
    CATEGORY_CHOICES = [
        (BREAKFAST, 'Breakfast'),
        (LUNCH, 'Lunch'),
        (DINNER, 'Dinner'),
        (DESSERT, 'Dessert'),
        (BEVERAGES, 'Beverage'),
    ]

    author = models.ForeignKey(get_user_model(), related_name='recipes', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    category = models.CharField(max_length=10, choices=CATEGORY_CHOICES, default=BREAKFAST)
    cover_image = models.ImageField(upload_to='recipe_images/', null=True, blank=True)
    description = models.CharField(max_length=500)
    content = RichTextField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'recipe'
        verbose_name_plural = 'recipes'
    
    def __str__(self):
        return self.title

recipe/forms.py
from django import forms
from .models import Recipe

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'category', 'description', 'cover_image', 'content' ]
        labels = {
            'title': 'Title',
            'category': 'Category',
            'description': 'Description',
            'content': '',
            'cover_image': 'Cover Image'
        }
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control form__title',
                'placeholder': 'Title'
            }),
            'category': forms.Select(attrs={
                'class': 'form-control form__category'
            }),
            'description': forms.TextInput(attrs={
                'class': 'form-control form__description',
                'placeholder': 'Description'
            }),
            'cover_image': forms.FileInput(attrs={
                'class': 'form-control form__cover-image'
            })
        }

recipe/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Recipe
from .forms import RecipeForm

# View for all the recipes page
@login_required
def all_recipes_view(request):
    recipes = Recipe.objects.all()
    return render(request, 'recipe/all_recipes.html', { 'recipes': recipes })

# View for the recipe detail page
@login_required
def recipe_detail_view(request, recipe_id):
    recipe = Recipe.objects.get(pk=recipe_id)
    return render(request, 'recipe/recipe_detail.html', { 'recipe': recipe })

# View for new recipe page
@login_required
def new_recipe_view(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.save()
            return redirect(reverse('recipe:recipe_detail', args=[recipe.id]))
    else:
        form = RecipeForm()
    return render(request, 'recipe/new_recipe.html', { 'form': form })

# View for the edit recipe page
@login_required
def update_recipe_view(request, recipe_id):
    recipe = Recipe.objects.get(pk=recipe_id)
    # If the user is not the author of the recipe, raise a 404
    if request.user != recipe.author:
        raise Http404('You are not the author of this recipe.')

    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES, instance=recipe)
        if form.is_valid():
            recipe = form.save()
            recipe.save()
            return redirect(reverse('recipe:recipe_detail', args=[recipe.id]))
    else:
        form = RecipeForm(instance=recipe)
    return render(request, 'recipe/update_recipe.html', { 'form': form, 'recipe': recipe })

# View for the delete recipe page
@login_required
def delete_recipe_view(request, recipe_id):
    recipe = Recipe.objects.get(pk=recipe_id)

    # If the user is not the author of the recipe, raise a 404
    if request.user != recipe.author:
        raise Http404('You are not the author of this recipe.')
    
    recipe.delete()
    return redirect(reverse('recipe:all_recipes'))

# View for the user's recipes page
@login_required
def user_recipes_view(request, user_id):
    user = get_user_model().objects.get(pk=user_id)
    recipes = Recipe.objects.filter(author=user.id)
    return render(request, 'recipe/user_recipes.html', {
        'recipes': recipes,
        'profile': user,
    })

# The explore page view
def explore(request):
    category = request.GET.get('category')
    query = request.GET.get('query')
    recipes = Recipe.objects.all()

    if category:
        recipes = recipes.filter(category=category)
    
    if query:
        recipes = recipes.filter(title__icontains=query)
    
    return render(request, 'recipe/explore.html', { 'recipes': recipes })

recipe/templates/recipe/all_recipes.html
{% extends "base.html" %}{% load static %}
{% block meta %}
    <!-- Open Graph Meta Tags (Facebook, LinkedIn) -->
    <meta property="og:title" content="Recipes Flavor Fusion">
    <meta property="og:description" content="All recipes on flavor fusion">
    <meta property="og:type" content="article">
    <meta property="og:url" content="{{ request.scheme }}://{{ request.host }}{% url 'recipe:all_recipes' %}">
    <meta property="og:image" content="{{ request.scheme }}://{{ request.host }}{% static 'core/img/flavor-fushion' %}">
    <meta property="og:image:width" content="900">
    <meta property="og:image:height" content="900">

    <!-- Twitter Card Meta Tags -->
    <meta name="twitter:card" content="Recipes Flavor Fusion">
    <meta name="twitter:title" content="Recipes Flavor Fusion">
    <meta name="twitter:description" content="All recipes on flavor fusion">
    <meta name="twitter:url" content="{{ request.scheme }}://{{ request.host }}{% url 'recipe:all_recipes' %}">
    <meta name="twitter:image" content="{{ request.scheme }}://{{ request.host }}{% static 'core/img/flavor-fushion' %}">
    <meta name="twitter:image:width" content="900">
    <meta name="twitter:image:height" content="900">

    <!-- Additional Meta Tags (optional) -->
    <meta name="author" content="Opaque Maniac">
    <meta name="description" content="all recipes on the flavor fushion platform">
{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'recipe/css/all_recipes.css' %}">
{% endblock css %}
{% block title %}All recipes{% endblock %}
{% block content %}

<!-- This section contains all recipes -->

<section class="section">
    <h2 class="section__title">All recipes</h2>
    <ul class="recipe__list">
        {% for recipe in recipes %}
        <li class="recipe__item">
            <a href="{% url 'recipe:recipe_detail' recipe.id %}" class="recipe__link">
                {% if recipe.cover_image %}
                    <img src="{{ recipe.cover_image.url }}" alt="{{ recipe.title }}" class="recipe__image">
                    {% else %}
                    <img src="{% static 'core/img/default.png' %}" alt="{{ recipe.title }}" class="recipe__image">
                {% endif %}
                <div class="recipe_detail">
                    <h3 class="recipe__title"><span>{{ recipe.title }}</span></h3>
                    <p class="recipe__author">By: <span>{{ recipe.author.first_name }} {{ recipe.author.last_name }}</span></p>
                    <p class="recipe__category">Category: <span>{{ recipe.category }}</span></p>
                    <p class="recipe__description">{{ recipe.description }}</p>
                    <p class="recipe__date-created">{{ recipe.date_created }}</p>
                </div>
            </a>
        </li>
        {% empty %}
        <p class="no__recipe-text">No recipes yet</p>
        {% endfor %}
    </ul>
</section>
{% endblock content %}
{% block js %}
    <script type="text/javascript" src="{% static 'recipe/js/all_recipes.js' %}"></script>
{% endblock js %}

recipe/templates/recipe/explore.html
{% extends "base.html" %}{% load static %}
{% block meta %}
    <!-- Open Graph Meta Tags (Facebook, LinkedIn) -->
    <meta property="og:title" content="Recipes Flavor Fusion">
    <meta property="og:description" content="All recipes on flavor fusion">
    <meta property="og:type" content="article">
    <meta property="og:url" content="{{ request.scheme }}://{{ request.host }}{% url 'recipe:all_recipes' %}">
    <meta property="og:image" content="{{ request.scheme }}://{{ request.host }}{% static 'core/img/flavor-fushion' %}">
    <meta property="og:image:width" content="900">
    <meta property="og:image:height" content="900">

    <!-- Twitter Card Meta Tags -->
    <meta name="twitter:card" content="Recipes Flavor Fusion">
    <meta name="twitter:title" content="Recipes Flavor Fusion">
    <meta name="twitter:description" content="All recipes on flavor fusion">
    <meta name="twitter:url" content="{{ request.scheme }}://{{ request.host }}{% url 'recipe:all_recipes' %}">
    <meta name="twitter:image" content="{{ request.scheme }}://{{ request.host }}{% static 'core/img/flavor-fushion' %}">
    <meta name="twitter:image:width" content="900">
    <meta name="twitter:image:height" content="900">

    <!-- Additional Meta Tags (optional) -->
    <meta name="author" content="Opaque Maniac">
    <meta name="description" content="all recipes on the flavor fushion platform">
{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'recipe/css/explore.css' %}">
{% endblock css %}
{% block title %}All recipes{% endblock %}
{% block content %}

<!-- This section contains all recipes -->

<section class="section">
    <div class="direction__button closed">
        <svg class="arrow__right show" width="800px" height="800px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M4 12H20M20 12L14 6M20 12L14 18" stroke="#1C274C" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        <svg class="arrow__left hidden" width="800px" height="800px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M10.5303 5.46967C10.8232 5.76256 10.8232 6.23744 10.5303 6.53033L5.81066 11.25H20C20.4142 11.25 20.75 11.5858 20.75 12C20.75 12.4142 20.4142 12.75 20 12.75H5.81066L10.5303 17.4697C10.8232 17.7626 10.8232 18.2374 10.5303 18.5303C10.2374 18.8232 9.76256 18.8232 9.46967 18.5303L3.46967 12.5303C3.17678 12.2374 3.17678 11.7626 3.46967 11.4697L9.46967 5.46967C9.76256 5.17678 10.2374 5.17678 10.5303 5.46967Z" fill="#1C274C"/>
        </svg>
    </div>
    <div class="side-nav">
        <div class="form__container">
            <form action="." method="get">
                {% csrf_token %}
                <input type="search" placholder="Query..." name="query">
                <button type="submit">Search...</button>
            </form>
        </div>
        <h3 class="categroy__title">Categories</h3>
        <div class="pagenav">
            <ul class="pagenav__list">
                <li class="pagenav__list--item">
                    <a href="{% url 'recipe:explore' %}?category=Breakfast" class="pagenav__link">Breakfast</a>
                </li>
                <li class="pagenav__list--item">
                    <a href="{% url 'recipe:explore' %}?category=Lunch" class="pagenav__link">Lunch</a>
                </li>
                <li class="pagenav__list--item">
                    <a href="{% url 'recipe:explore' %}?category=Dinner" class="pagenav__link">Dinner</a>
                </li>
                <li class="pagenav__list--item">
                    <a href="{% url 'recipe:explore' %}?category=Dessert" class="pagenav__link">Dessert</a>
                </li>
                <li class="pagenav__list--item">
                    <a href="{% url 'recipe:explore' %}?category=Beverages" class="pagenav__link">Beverages</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="page-main">
        <h2 class="page__title">Recipes</h2>
        <div class="post__container">
            <ul class="recipe__list">
                {% for recipe in recipes %}
                    <li class="recipe__list--item">
                        <a href="" class="recipe__link">
                            {% if recipe.cover_image %}
                                <img src="{{ recipe.cover_image.url }}" alt="{{ recipe.title }}" class="recipe__image">
                            {% else %}
                                <img src="{% static 'core/img/default.png' %}" alt="{{ recipe.title }}" class="recipe__image">
                            {% endif %}
                            <div class="recipe_detail">
                                <h3 class="recipe__title"><span>{{ recipe.title }}</span></h3>
                                <p class="recipe__author">By: <span>{{ recipe.author.first_name }} {{ recipe.author.last_name }}</span></p>
                                <p class="recipe__category">Category: <span>{{ recipe.category }}</span></p>
                                <p class="recipe__description">{{ recipe.description }}</p>
                                <p class="recipe__date-created">{{ recipe.date_created }}</p>
                            </div>
                        </a>
                    </li>
                {% empty %}
                    <p class="no__recipe-text">No recipes yet!</p>
                {% endfor %}
            </ul>
        </div>
    </div>
</section>
{% endblock content %}
{% block js %}
    <script type="text/javascript" src="{% static 'recipe/js/explore.js' %}"></script>
{% endblock js %}

recipe/templates/recipe/new_recipe.html
{% extends "base.html" %}{% load static %}
{% block meta %}
    <!-- Open Graph Meta Tags (Facebook, LinkedIn) -->
    <meta property="og:title" content="Create New Recipes Flavor Fusion">
    <meta property="og:description" content="Create a recipes on flavor fusion">
    <meta property="og:type" content="website">
    <meta property="og:url" content="{{ request.scheme }}://{{ request.host }}{% url 'recipe:new_recipe' %}">
    <meta property="og:image" content="{{ request.scheme }}://{{ request.host }}{% static 'core/img/flavor-fushion' %}">
    <meta property="og:image:width" content="900">
    <meta property="og:image:height" content="900">

    <!-- Twitter Card Meta Tags -->
    <meta name="twitter:card" content="Create New Recipes Flavor Fusion">
    <meta name="twitter:title" content="Create New Recipes Flavor Fusion">
    <meta name="twitter:description" content="Create a new recipe to share on flavor fusion">
    <meta name="twitter:url" content="{{ request.scheme }}://{{ request.host }}{% url 'recipe:new_recipe' %}">
    <meta name="twitter:image" content="{{ request.scheme }}://{{ request.host }}{% static 'core/img/flavor-fushion' %}">
    <meta name="twitter:image:width" content="900">
    <meta name="twitter:image:height" content="900">

    <!-- Additional Meta Tags (optional) -->
    <meta name="author" content="Opaque Maniac">
    <meta name="description" content="create and share a new recipe on flavor fushion">
{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'recipe/css/new_recipe.css' %}">
{% endblock css %}
{% block title %}New Recipe{% endblock %}
{% block content %}

<!-- This is a template for a new recipe -->

<section class="section">
    <h1 class="title">New Recipe</h2>
    <form class="recipe_form" method="POST" action=".">
        {% csrf_token %}
        <div class="form-outline">
            {% for field in form %}
                <div class="field__container">
                    <div>
                        <label for="field.label" class="field__label">{{ field.label }}</label>
                        {{ field }}
                    </div>
                </div>
                
            {% endfor %}
            <br>
        </div>  
        <div class="media">
            <!--Blog Text Area-->
            {{form.media}}
        </div>
        <button type="submit" class="submit__button">Submit</button>
    </form>
</section>
{% endblock content %}
{% block js %}
    <script type="text/javascript" src="{% static 'recipe/js/new_recipe.js' %}"></script>
{% endblock js %}

recipe/templates/recipe/recipe_detail.html
{% extends "base.html" %}{% load static %}
{% block meta %}
    <!-- For the bot -->
    <meta name="robots" content="nofollow">

    <!-- Open Graph Meta Tags (Facebook, LinkedIn) -->
    <meta property="og:title" content="{{ recipe.title }}">
    <meta property="og:description" content="{{ recipe.description }}">
    <meta property="og:type" content="article">
    <meta property="og:url" content="{{ request.scheme }}://{{ request.host }}{% url 'recipe:recipe_detail' recipe.id %}">
    {% if recipe.cover_image %}
        <meta property="og:image" content="{{ request.scheme }}://{{ request.host }}{{ recipe.cover_image.url }}">
    {% else %}
        <meta property="og:image" content="{{ request.scheme }}://{{ request.host }}{% static 'core/img/default.png' %}">
    {% endif %}
    <meta property="og:image:width" content="900">
    <meta property="og:image:height" content="900">

    <!-- Twitter Card Meta Tags -->
    <meta name="twitter:card" content="{{ recipe.title }}">
    <meta name="twitter:title" content="{{ recipe.title }}">
    <meta name="twitter:description" content="{{ recipe.description }}">
    <meta name="twitter:url" content="{{ request.scheme }}://{{ request.host }}{% url 'recipe:recipe_detail' recipe.id %}">
    {% if recipe.cover_image %}
        <meta name="twitter:image" content="{{ recipe.cover_image.url }}">
    {% else %}
        <meta name="twitter:image" content="{% static 'core/img/default.png' %}">
    {% endif %}
    <meta name="twitter:image:width" content="900">
    <meta name="twitter:image:height" content="900">

    <!-- Additional information about the recipe -->
    <meta property="article:published_time" content="{{ recipe.date_created }}">
    <meta property="article:modified_time" content="{{ recipe.date_updated }}">

    <!-- Additional Meta Tags (optional) -->
    <meta name="author" content="{{ recipe.author.first_name }} {{ recipe.author.last_name }}">
    <meta name="description" content="All recipes on the flavor fushion platform">
{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'recipe/css/recipe_detail.css' %}">
{% endblock css %}
{% block title %}{{ recipe.title }}{% endblock %}
{% block content %}

<!-- This section contains an individual recipe -->

<section class="section">
    <h2 class="recipe__title">{{ recipe.title }}</h2>
    <div class="recipe__top">
        <div class="recipe__detail">
            <p class="recipe__description">{{ recipe.description }}</p>
            <p class="recipe__category">Category: <a href="#">{{ recipe.category }}</a></p>
            <p class="recipe__date-created">Created on {{ recipe.date_created }}</p>
            <p class="recipe__date-updated">Last updated on {{ recipe.date_updated }}</p>
            {% if request.user == recipe.author %}
            <div class="recipe__actions">
                <a href="{% url 'recipe:update_recipe' recipe.id %}" class="btn btn--primary">Update</a>
                <a href="{% url 'recipe:delete_recipe' recipe.id %}" class="btn btn--danger">Delete</a>
            </div>
            {% endif %}
            <p class="recipe__author">By <span><a href="{% url 'recipe:user_recipes' recipe.author.id %}">{{ recipe.author.first_name }} {{ recipe.author.last_name }}</a></span></p>
        </div>
        <div class="recipe__image">
            {% if recipe.cover_image %}
                <img src="{{ recipe.cover_image.url }}" alt="{{ recipe.title }}">
            {% else %}
                <img src="{% static 'core/img/default.png' %}" alt="{{ recipe.title }}">
            {% endif %}
        </div>
    </div>

    <hr>
    <div class="recipe__content">
        <article>
            {{ recipe.content|safe }}
        </article>
    </div>
</section>
{% endblock content %}
{% block js %}
{% endblock js %}

recipe/templates/recipe/update_recipe.html
{% extends "base.html" %}{% load static %}
{% block meta %}
    <!-- Meta tags for bots -->
    <meta name="googlebot" content="noindex">
    <meta name="googlebot-news" content="nosnippet">
    <meta name="robots" content="noindex">
    <meta name="robots" content="noarchive">
    <meta name="robots" content="nofollow">
    <meta name="robots" content="nosnippet">
    <meta name="robots" content="noimageindex">
    <meta name="robots" content="noodp">
    <meta name="robots" content="noydir">
    <meta name="robots" content="nocache">
{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'recipe/css/update_recipe.css' %}">
{% endblock css %}
{% block title %}Update Recipe{% endblock %}
{% block content %}
<!-- Form to update a recipe-->

<section class="section">
    <h1 class="title">Update Recipe</h2>
    <form class="recipe_form" method="POST" action=".">
        {% csrf_token %}
        <div class="form-outline">
            {{form.as_p}}
            <br>
        </div>  
        <!--Blog Text Area-->
        {{form.media}}
        <input type="submit">
    </form>
</section>
{% endblock content %}
{% block js %}
    <script type="text/javascript" src="{% static 'recipe/js/update_recipe.js' %}"></script>
{% endblock js %}

recipe/templates/recipe/user_recipes.html
{% extends "base.html" %}{% load static %}
{% block meta %}
    <!-- Open Graph Meta Tags (Facebook, LinkedIn) -->
    <meta property="og:title" content="Recipes by {{ profile.first_name }}">
    <meta property="og:description" content="All recipes by {{ profile.first_name }} {{ profile.last_name }}">
    <meta property="og:type" content="website">
    <meta property="og:url" content="{{ request.scheme }}://{{ request.host }}{% url 'recipe:user_recipes' profile.id %}">
    <meta property="og:image" content="{{ request.scheme }}://{{ request.host }}{% static 'core/img/flavor-fushion' %}">
    <meta property="og:image:width" content="900">
    <meta property="og:image:height" content="900">

    <!-- Twitter Card Meta Tags -->
    <meta name="twitter:card" content="Recipes by {{ profile.first_name }}">
    <meta name="twitter:title" content="Recipes by {{ profile.first_name }}">
    <meta name="twitter:description" content="All recipes by {{ profile.first_name }} {{ profile.last_name }}">
    <meta name="twitter:url" content="{{ request.scheme }}://{{ request.host }}{% url 'recipe:user_recipes' profile.id %}">
    <meta name="twitter:image" content="{{ request.scheme }}://{{ request.host }}{% static 'core/img/flavor-fushion' %}">
    <meta name="twitter:image:width" content="900">
    <meta name="twitter:image:height" content="900">

    <!-- Additional Meta Tags (optional) -->
    <meta name="author" content="{{ profile.first_name }} {{ profile.last_name }}">
    <meta name="description" content="all recipes by {{ profile.first_name }} {{ profile.last_name }}">
{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'recipe/css/user_recipes.css' %}">
{% endblock css %}
{% block title %}{{ recipe.author.first_name }} {{ recipe.author.last_name}}{% endblock %}
{% block content %}

<!-- This is a template for recipes for a user -->
<section class="section">
    <h2 class="section__title">All recipes by {{ profile.first_name }} {{ profile.last_name }}</h2>
    <h3 class="section__subtitle">Recipes</h3>
    <article class="recipes">
        <ul class="recipe__list">
            {% for recipe in recipes %}
            <li class="recipe__item">
                <a href="{% url 'recipe:recipe_detail' recipe.id %}" class="recipe__link">
                    {% if recipe.cover_image %}
                    <img src="{{ recipe.cover_image.url }}" alt="{{ recipe.title }}" class="recipe__image">
                    {% else %}
                    <img src="{% static 'core/img/default.png' %}" alt="{{ recipe.title }}" class="recipe__image">
                    {% endif %}
                    <h3 class="recipe__title">{{ recipe.title }}</h3>
                </a>
            </li>
            {% empty %}
            <p class="no__recipe-text">No recipes yet</p>
            {% endfor %}
        </ul>
    </article>
</section>
{% endblock content %}
{% block js %}
{% endblock js %}