config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('users.urls')),
    path('recipe/', include('recipe.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import (
    home_view,
    about_view,
    contact_view,
    terms_view,
)

app_name = 'core'

# Path: core/urls.py
urlpatterns = [
    path('', home_view, name='home'),
    path('about/', about_view, name='about'),
    path('contact/', contact_view, name='contact'),
    path('terms/', terms_view, name='terms'),
]

recipe/urls.py
from django.urls import path
from .views import (
    all_recipes_view,
    recipe_detail_view,
    new_recipe_view,
    update_recipe_view,
    delete_recipe_view,
    user_recipes_view,
    explore,
)

app_name = 'recipe'

# Path: recipe/urls.py
urlpatterns = [
    path('all/', all_recipes_view, name='all_recipes'),
    path('new/', new_recipe_view, name='new_recipe'),
    path('<int:recipe_id>/', recipe_detail_view, name='recipe_detail'),
    path('<int:recipe_id>/update/', update_recipe_view, name='update_recipe'),
    path('<int:recipe_id>/delete/', delete_recipe_view, name='delete_recipe'),
    path('user/<int:user_id>/', user_recipes_view, name='user_recipes'),
    path('explore/', explore, name="explore"),
]

users/urls.py
from django.urls import path
from .views import (
    register_view,
    login_view,
    logout_view,
    profile_view,
    edit_profile_view,
    
)

app_name = 'users'

# Path: users/urls.py
urlpatterns = [
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/', profile_view, name='profile'),
    path('profile/edit/',edit_profile_view, name='edit_profile'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

# View for the home page
def home_view(request):
    return render(request, 'core/home.html')

# View for the about page
def about_view(request):
    return render(request, 'core/about.html')

# View for the contact page
def contact_view(request):
    return render(request, 'core/contact.html')

# View for the terms page
def terms_view(request):
    return render(request, 'core/terms.html')

# View for the 404 page
def handler404(request, exception):
    return render(request, 'core/404.html', status=404)

# View for the 500 page
def handler500(request):
    return render(request, 'core/500.html', status=500)

core/templates/base.html
<!-- This is the base file where all the other files will inherit form -->
<!DOCTYPE html>{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--Inter font family -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">

    <!--Dancing script font family -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet">

    <!-- The favicon for this template -->
    <link rel="icon" href="{% static 'core/img/noodles-image.png' %}">

    <!-- Theme color for the template -->
    <link rel="theme-color" href="#F9A825">

    <!-- Meta tags for this template -->
    <meta name="keywords" content="recipe, food, cooking, delicious, tasty, healthy">
    {% block meta %}
    {% endblock meta %}

    <!-- stylesheets for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'core/css/main.css' %}">
    {% block css %}
    {% endblock css %}
    <title>{% block title %}{% endblock title %} | FlavorFusion</title>
</head>

<body>
    <div class="main-container">
        {% include 'header.html' %}

        <!-- The page content -->
        <main class="main">
            {% block content %}
            {% endblock content %}
        </main>

        {% include 'footer.html' %}
    </div>
    <div class="page-backgroud">
    </div>

    <!-- The javascript code for this template -->
    <script type="text/javascript" src="{% static 'core/js/main.js' %}" type="text/javascript"></script>
    {% block js %}
    {% endblock js %}
</body>

</html>

core/templates/footer.html
<!-- This is the footer section -->

<footer class="footer">
    <h2 class="footer__title">Thanks for visiting</h2>
    <nav class="footer__nav">
        <ul class="footer__list">
            <p class="footer__list-title">Quick Links</p>
            <li class="footer__list-item"><a href="{% url 'core:about' %}">About</a></li>
            <li class="footer__list-item"><a href="{% url 'core:contact' %}">Contact</a></li>
            <li class="footer__list-item"><a href="{% url 'recipe:all_recipes' %}">Recipes</a></li>
            <li class="footer__list-item"><a href="{% url 'core:terms' %}">Terms & Condition</a></li>
        </ul>
    </nav>
    <p class="footer__copyright"></p>
</footer>

<script type="text/javascript">
    let year = new Date().getFullYear();
    document.querySelector('.footer__copyright').textContent = `© ${year} - ${year + 1} Flavor Fusion`;
</script>

core/templates/header.html
<!-- This is the page header -->

<header class="header">
    <div class="header__info">
        <a href="{% url 'core:home' %}" class="header__title">
            <!-- SVG for the page icon -->
            <svg class="header__title-icon" version="1.0" xmlns="http://www.w3.org/2000/svg" width="48.000000pt"
                height="48.000000pt" viewBox="0 0 48.000000 48.000000" preserveAspectRatio="xMidYMid meet">

                <g transform="translate(0.000000,48.000000) scale(0.100000,-0.100000)" fill="#000000" stroke="none">
                    <path d="M350 433 c-65 -6 -69 -19 -5 -15 30 2 55 8 55 13 0 5 -1 8 -2 7 -2
                        -1 -23 -3 -48 -5z" />
                    <path d="M290 370 c0 -5 25 -10 55 -10 30 0 55 5 55 10 0 6 -25 10 -55 10 -30
                        0 -55 -4 -55 -10z" />
                    <path d="M75 139 c9 -17 32 -40 51 -51 19 -11 34 -26 34 -33 0 -18 23 -25 80
                        -25 57 0 80 7 80 25 0 7 15 22 34 33 19 11 42 34 51 51 l16 31 -181 0 -181 0
                        16 -31z" />
                </g>
            </svg>
            <h1 class="header__title-text">FlavorFusion</h1>
        </a>
    </div>
    <!-- SVG for the menu icon -->
    <svg class="menu__icon" id="menu-icon" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="24" height="24"
        viewBox="0 0 24 24">
        <path
            d="M 2 5 L 2 7 L 22 7 L 22 5 L 2 5 z M 2 11 L 2 13 L 22 13 L 22 11 L 2 11 z M 2 17 L 2 19 L 22 19 L 22 17 L 2 17 z">
        </path>
    </svg>
    <!-- SVG for the x icon -->
    <svg class="menu__icon hidden" id="x-icon" xmlns="http://www.w3.org/2000/svg" width="16" height="16"
        fill="currentColor" class="bi bi-x" viewBox="0 0 16 16">
        <path
            d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
    </svg>
</header>

<!-- The page navigation -->
<nav class="navbar navbar-hide">
    <ul class="navbar__list">
        <li class="navbar__list-item"><a href="{% url 'core:home' %}">Home</a></li>
        <li class="navbar__list-item"><a href="{% url 'core:about' %}">About</a></li>
        <li class="navbar__list-item"><a href="{% url 'core:contact' %}">Contact</a></li>
        <li class="navbar__list-item"><a href="{% url 'core:terms' %}">Terms & Condition</a></li>
        {% if user.is_authenticated %}
        <li class="navbar__list-item"><a href="{% url 'recipe:explore' %}">Explore</a></li>
        <li class="navbar__list-item"><a href="{% url 'recipe:all_recipes' %}">All Recipes</a></li>
        <li class="navbar__list-item"><a href="{% url 'recipe:new_recipe' %}">New Recipes</a></li>
        <li class="navbar__list-item"><a href="{% url 'users:profile' %}">Profile</a></li>
        <li class="navbar__list-item"><a href="{% url 'users:logout' %}">Logout</a></li>
        {% else %}
        <li class="navbar__list-item"><a href="{% url 'users:login' %}">Login</a></li>
        <li class="navbar__list-item"><a href="{% url 'users:register' %}">Register</a></li>
        {% endif %}
    </ul>
</nav>

core/templates/test_form.html
{{ form.as_p }}